// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/google-gemini-cli.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const GOOGLE_GEMINI_CLI_MODELS: ModelCatalog<typeof values, "google-gemini-cli"> =
	flattenModelCatalog("google-gemini-cli", values);
